// convpng v6.8
// this file contains all the graphics sources for easy inclusion in a project
#ifndef __logo_gfx__
#define __logo_gfx__
#include <stdint.h>

#define logo_gfx_transparent_color_index 0

#define bomb_width 32
#define bomb_height 32
#define bomb_size 1026
extern uint8_t bomb_data[1026];
#define bomb ((gfx_sprite_t*)bomb_data)
#define strawberry_width 32
#define strawberry_height 32
#define strawberry_size 1026
extern uint8_t strawberry_data[1026];
#define strawberry ((gfx_sprite_t*)strawberry_data)
#define watermelon_width 32
#define watermelon_height 32
#define watermelon_size 1026
extern uint8_t watermelon_data[1026];
#define watermelon ((gfx_sprite_t*)watermelon_data)
#define pineapple_width 32
#define pineapple_height 32
#define pineapple_size 1026
extern uint8_t pineapple_data[1026];
#define pineapple ((gfx_sprite_t*)pineapple_data)
#define apple_width 32
#define apple_height 32
#define apple_size 1026
extern uint8_t apple_data[1026];
#define apple ((gfx_sprite_t*)apple_data)
#define red_apple_width 32
#define red_apple_height 32
#define red_apple_size 1026
extern uint8_t red_apple_data[1026];
#define red_apple ((gfx_sprite_t*)red_apple_data)
#define pear_width 32
#define pear_height 32
#define pear_size 1026
extern uint8_t pear_data[1026];
#define pear ((gfx_sprite_t*)pear_data)
#define grapes_width 32
#define grapes_height 32
#define grapes_size 1026
extern uint8_t grapes_data[1026];
#define grapes ((gfx_sprite_t*)grapes_data)
#define kiwi_width 32
#define kiwi_height 32
#define kiwi_size 1026
extern uint8_t kiwi_data[1026];
#define kiwi ((gfx_sprite_t*)kiwi_data)
#define banana_width 32
#define banana_height 32
#define banana_size 1026
extern uint8_t banana_data[1026];
#define banana ((gfx_sprite_t*)banana_data)
#define pomegranate_width 32
#define pomegranate_height 32
#define pomegranate_size 1026
extern uint8_t pomegranate_data[1026];
#define pomegranate ((gfx_sprite_t*)pomegranate_data)
#define coconut_width 32
#define coconut_height 32
#define coconut_size 1026
extern uint8_t coconut_data[1026];
#define coconut ((gfx_sprite_t*)coconut_data)
#define lemon_width 32
#define lemon_height 32
#define lemon_size 1026
extern uint8_t lemon_data[1026];
#define lemon ((gfx_sprite_t*)lemon_data)
#define lime_width 32
#define lime_height 32
#define lime_size 1026
extern uint8_t lime_data[1026];
#define lime ((gfx_sprite_t*)lime_data)
#define orange_width 32
#define orange_height 32
#define orange_size 1026
extern uint8_t orange_data[1026];
#define orange ((gfx_sprite_t*)orange_data)
#define watermelon_top_width 32
#define watermelon_top_height 32
#define watermelon_top_size 1026
extern uint8_t watermelon_top_data[1026];
#define watermelon_top ((gfx_sprite_t*)watermelon_top_data)
#define watermelon_bottom_width 32
#define watermelon_bottom_height 32
#define watermelon_bottom_size 1026
extern uint8_t watermelon_bottom_data[1026];
#define watermelon_bottom ((gfx_sprite_t*)watermelon_bottom_data)
#define strawberry_top_width 32
#define strawberry_top_height 32
#define strawberry_top_size 1026
extern uint8_t strawberry_top_data[1026];
#define strawberry_top ((gfx_sprite_t*)strawberry_top_data)
#define strawberry_bottom_width 32
#define strawberry_bottom_height 32
#define strawberry_bottom_size 1026
extern uint8_t strawberry_bottom_data[1026];
#define strawberry_bottom ((gfx_sprite_t*)strawberry_bottom_data)
#define pineapple_top_width 32
#define pineapple_top_height 32
#define pineapple_top_size 1026
extern uint8_t pineapple_top_data[1026];
#define pineapple_top ((gfx_sprite_t*)pineapple_top_data)
#define pineapple_bottom_width 32
#define pineapple_bottom_height 32
#define pineapple_bottom_size 1026
extern uint8_t pineapple_bottom_data[1026];
#define pineapple_bottom ((gfx_sprite_t*)pineapple_bottom_data)
#define pear_top_width 32
#define pear_top_height 32
#define pear_top_size 1026
extern uint8_t pear_top_data[1026];
#define pear_top ((gfx_sprite_t*)pear_top_data)
#define pear_bottom_width 32
#define pear_bottom_height 32
#define pear_bottom_size 1026
extern uint8_t pear_bottom_data[1026];
#define pear_bottom ((gfx_sprite_t*)pear_bottom_data)
#define apple_top_width 32
#define apple_top_height 32
#define apple_top_size 1026
extern uint8_t apple_top_data[1026];
#define apple_top ((gfx_sprite_t*)apple_top_data)
#define apple_bottom_width 32
#define apple_bottom_height 32
#define apple_bottom_size 1026
extern uint8_t apple_bottom_data[1026];
#define apple_bottom ((gfx_sprite_t*)apple_bottom_data)
#define red_apple_top_width 32
#define red_apple_top_height 32
#define red_apple_top_size 1026
extern uint8_t red_apple_top_data[1026];
#define red_apple_top ((gfx_sprite_t*)red_apple_top_data)
#define red_apple_bottom_width 32
#define red_apple_bottom_height 32
#define red_apple_bottom_size 1026
extern uint8_t red_apple_bottom_data[1026];
#define red_apple_bottom ((gfx_sprite_t*)red_apple_bottom_data)
#define grape_top_width 32
#define grape_top_height 32
#define grape_top_size 1026
extern uint8_t grape_top_data[1026];
#define grape_top ((gfx_sprite_t*)grape_top_data)
#define grape_bottom_width 32
#define grape_bottom_height 32
#define grape_bottom_size 1026
extern uint8_t grape_bottom_data[1026];
#define grape_bottom ((gfx_sprite_t*)grape_bottom_data)
#define kiwi_top_width 32
#define kiwi_top_height 32
#define kiwi_top_size 1026
extern uint8_t kiwi_top_data[1026];
#define kiwi_top ((gfx_sprite_t*)kiwi_top_data)
#define kiwi_bottom_width 32
#define kiwi_bottom_height 32
#define kiwi_bottom_size 1026
extern uint8_t kiwi_bottom_data[1026];
#define kiwi_bottom ((gfx_sprite_t*)kiwi_bottom_data)
#define banana_top_width 32
#define banana_top_height 32
#define banana_top_size 1026
extern uint8_t banana_top_data[1026];
#define banana_top ((gfx_sprite_t*)banana_top_data)
#define banana_bottom_width 32
#define banana_bottom_height 32
#define banana_bottom_size 1026
extern uint8_t banana_bottom_data[1026];
#define banana_bottom ((gfx_sprite_t*)banana_bottom_data)
#define coconut_top_width 32
#define coconut_top_height 32
#define coconut_top_size 1026
extern uint8_t coconut_top_data[1026];
#define coconut_top ((gfx_sprite_t*)coconut_top_data)
#define coconut_bottom_width 32
#define coconut_bottom_height 32
#define coconut_bottom_size 1026
extern uint8_t coconut_bottom_data[1026];
#define coconut_bottom ((gfx_sprite_t*)coconut_bottom_data)
#define lemon_top_width 32
#define lemon_top_height 32
#define lemon_top_size 1026
extern uint8_t lemon_top_data[1026];
#define lemon_top ((gfx_sprite_t*)lemon_top_data)
#define lemon_bottom_width 32
#define lemon_bottom_height 32
#define lemon_bottom_size 1026
extern uint8_t lemon_bottom_data[1026];
#define lemon_bottom ((gfx_sprite_t*)lemon_bottom_data)
#define lime_top_width 32
#define lime_top_height 32
#define lime_top_size 1026
extern uint8_t lime_top_data[1026];
#define lime_top ((gfx_sprite_t*)lime_top_data)
#define lime_bottom_width 32
#define lime_bottom_height 32
#define lime_bottom_size 1026
extern uint8_t lime_bottom_data[1026];
#define lime_bottom ((gfx_sprite_t*)lime_bottom_data)
#define orange_top_width 32
#define orange_top_height 32
#define orange_top_size 1026
extern uint8_t orange_top_data[1026];
#define orange_top ((gfx_sprite_t*)orange_top_data)
#define orange_bottom_width 32
#define orange_bottom_height 32
#define orange_bottom_size 1026
extern uint8_t orange_bottom_data[1026];
#define orange_bottom ((gfx_sprite_t*)orange_bottom_data)
#define sizeof_logo_gfx_pal 512
extern uint16_t logo_gfx_pal[256];

#endif
